### ISSUE TITLE
Add Event Update Route

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-kiosk-backend#26]
Right now we have no ability to update an event.

**Comment by kcouv** [comment]
Progress: almost done, **needs google sheet range updated** to reflect # of rows/cols in event sheet. Then **needs tested**.

Also, a **delete route** crossed my mind, so might be useful to make one in the future, but **not necessary for MVP**. Only accessible by whoever is handling the data though, wouldn't trust myself with a delete power lol.

**Comment by SpBills** [comment]
@kcouv https://github.com/CreativeSolutionsGroup/smart-events-kiosk-backend/issues/28
