### ISSUE TITLE
Receive heartbeat from frontend and log name

### ISSUE THREAD

**Issue by SebastianNeiswanger** [CreativeSolutionsGroup/smart-events-kiosk-backend#7]

**Comment by kcouv** [comment]
https://github.com/mdn/samples-server/tree/master/s/websocket-chat
might be helpful

**Comment by SebastianNeiswanger** [comment]
[https://medium.com/factory-mind/websocket-node-js-express-step-by-step-using-typescript-725114ad5fe4](url) could also be helpful with a step by step
